# Generated by Django 3.2.4 on 2021-06-04 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Url',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('long_url', models.URLField()),
                ('short_id', models.SlugField()),
                ('counter', models.IntegerField(default=0)),
            ],
        ),
    ]
